### ISSUE TITLE
timerExists assert hit in ~Timer() when destroyed from DeletedAtShutdown

### ISSUE THREAD

**Issue by jearnshaw** [julianstorer/JUCE#102]
If creating & deleting a Timer class from an DeletedAtShutdown object it is possible to hit the following assert in removeTimer()

`
    void removeTimer (Timer* const t) noexcept
    {
       #if JUCE_DEBUG
        // trying to remove a timer that's not here - shouldn't get to this point,
        // so if you get this assertion, let me know!
        jassert (timerExists (t));
       #endif
`

The issue can be seen under the following circumstances:

1.  A Timer/DeletedAtShutdown object is created
2.  startTimer() creates Timer::TimerThead
3.  DeletedAtShutdown::deleteAll() called
4.  Timer::TimerThread destroyed
5.  startTimer() creates a new Timer::TimerThead
6.  Timer/DeletedAtShutdown destroyed
7.   Timer/DeletedAtShutdown removeTimer() called on new Timer::TimerThead which asserts

**Comment by julianstorer** [comment]
Surely the only way to make that happen is if you start a timer in the *destructor* of your DeletedAtShutdown object! 

There are infinitely many ways in which carelessness inside destructors of objects during shutdown can cause havoc, which is why you always need to be specially careful there. I don't think this case is particularly deserving of any kind of workaround to avoid the assertion - you just need to not go creating timers (or anything else!) while objects are being destroyed!

**Comment by jearnshaw** [comment]
It is possible for another thread which hasn't been stopped yet to call startTimer() under normal operation causing the Timer::TimerThead to be recreated. Surely Timer::TimerThead should not be able to be deleted while there are active Timer objects with Timers running.
